dist: trusty
sudo: required
language: rust
cache: cargo
addons:
  apt:
    packages:
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev
      - binutils-dev
      - cmake
    sources:
      - kalakris-cmake

rust:
  - nightly

script:
  - cargo build
  - cargo test
  - cargo doc --no-deps

after_success:
  - if [ "$TRAVIS_RUST_VERSION" == "nightly" ]; then
        cargo bench;
    fi
  - cargo coveralls --verbose --exclude-pattern '/parquet-rs/src/bin'
  - '[ "$TRAVIS_PULL_REQUEST" = false ] &&
    { [ "$TRAVIS_TAG" != "" ] || [ "$TRAVIS_BRANCH" = "master" ]; } &&
    ./ci/deploy-docs.sh'
env:
  global:
    - TRAVIS_CARGO_NIGHTLY_FEATURE=""
    - RUST_BACKTRACE=1
