[package]
name = "parquet-rs"
version = "0.1.0"
authors = ["Chao Sun <sunchao@apache.org>"]

[dependencies]
quick-error = "1.1.0"
byteorder = "1"
ordered-float = "0.4.0"
try_from = "0.2.1"

# TODO: use the official repo
thrift = { git = "https://github.com/sunchao/thrift" }