[package]
name = "parquet"
version = "0.1.0"
license = "Apache-2.0"
description = "Apache Parquet implementation in Rust"
authors = ["Chao Sun <sunchao@apache.org>"]
homepage = "https://github.com/sunchao/parquet-rs"
repository = "https://github.com/sunchao/parquet-rs"
keywords = ["parquet", "hadoop"]

[dependencies]
quick-error = "1.1.0"
byteorder = "1"
ordered-float = "0.4.0"
try_from = "0.2.1"
snap = "0.2"
brotli = "1.0.7"
flate2 = "0.2"
rand = "0.3"
thrift = "0.0.4"